version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
